# docker-compose.yml
version: '3'
services:

  flask:
    image: py-conversion-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - "./:/app"
  # nginx:
  #   image: webapp-nginx
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-nginx
  #   ports:
  #     - 5000:80
  #   depends_on:
  #     - flask